[package]
name = "napi_sandbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-std = "1.12.0"

[dependencies.neon]
# version = "2"
path = "/Volumes/Storage/Development/alshdavid-forks/neon/crates/neon"
features = ["async_local"]

